### ISSUE TITLE
How to access Traefik dashboard?

### ISSUE THREAD

**Issue by yashodhank** [raph6/docker-traefik#1]
Thank you for sharing!

I tried to connecting to port 8080 soon after docker-compose up -d as mentioned in help. But there seems to be dashboard missing?

**Comment by raph6** [comment]
Hello, thank you for using this repository !

You can access to dashboard by connecting to url set in environment variable `TRAEFIK_URL` 

If you want to access with the port 8080, you can edit the file `traefik/docker-compose.yml` like this 

```yml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
```
